/* This file is autogenerated, do not edit*/
#include "PointerCoordinates-static_automoc.dir/moc_PointerCoordin_PNXPKKPOAT6JAJ.cpp"
#include "PointerCoordinates-static_automoc.dir/moc_PointerCoordin_ZW6VPGHZK6ZOGE.cpp"
