/* This file is autogenerated, do not edit*/
#include "TelescopeControl-static_automoc.dir/moc_TelescopeContr_IUCFT3XN2EFXE7.cpp"
#include "TelescopeControl-static_automoc.dir/moc_TelescopeClien_GBT2QJELQRCB52.cpp"
#include "TelescopeControl-static_automoc.dir/moc_TelescopeClien_ALRYL4MBJHZ6VJ.cpp"
#include "TelescopeControl-static_automoc.dir/moc_TelescopeClien_XNJ5Y3II7BXGLV.cpp"
#include "TelescopeControl-static_automoc.dir/moc_SlewDialog_SYWYLTBF6QTQEU.cpp"
#include "TelescopeControl-static_automoc.dir/moc_StoredPointsDi_ZO2UWIJ2EFNN4A.cpp"
#include "TelescopeControl-static_automoc.dir/moc_TelescopeConfi_DFE6FG3E23WFMB.cpp"
#include "TelescopeControl-static_automoc.dir/moc_TelescopeDialo_PUDHFHDAMN3AZH.cpp"
