/* This file is autogenerated, do not edit*/
#include "EquationOfTime-static_automoc.dir/moc_EquationOfTime_UBZSYDJ2A2TD4I.cpp"
#include "EquationOfTime-static_automoc.dir/moc_EquationOfTime_O4HTTGFFOTQMUJ.cpp"
