/* This file is autogenerated, do not edit*/
#include "AngleMeasure-static_automoc.dir/moc_AngleMeasure_ZIBPKHD3IN52EX.cpp"
#include "AngleMeasure-static_automoc.dir/moc_AngleMeasureDi_LPKIAYJPEW2PEU.cpp"
