/* This file is autogenerated, do not edit*/
#include "Oculars-static_automoc.dir/moc_CCD_Y4X2PXRNAO3Y4W.cpp"
#include "Oculars-static_automoc.dir/moc_Lens_TMXZIF4WNAE2FP.cpp"
#include "Oculars-static_automoc.dir/moc_Ocular_RPCBIOE4EKT7TR.cpp"
#include "Oculars-static_automoc.dir/moc_Oculars_EJIH65JJDSHEAU.cpp"
#include "Oculars-static_automoc.dir/moc_Telescope_7JF7U3XCWPAC5J.cpp"
#include "Oculars-static_automoc.dir/moc_OcularDialog_VIII4AITLWRKAY.cpp"
#include "Oculars-static_automoc.dir/moc_OcularsGuiPane_XJZCUFY2BHYSLI.cpp"
#include "Oculars-static_automoc.dir/moc_PropertyBasedT_N56B46HHKJU4SH.cpp"
