/* This file is autogenerated, do not edit*/
#include "Satellites-static_automoc.dir/moc_Satellites_6KJGVCBPTTMELX.cpp"
#include "Satellites-static_automoc.dir/moc_SatellitesList_J7Z2APISK5LGSJ.cpp"
#include "Satellites-static_automoc.dir/moc_SatellitesList_S3T2QANLJBPC3H.cpp"
#include "Satellites-static_automoc.dir/moc_SatellitesDial_HAR2JZ4BWKNSXN.cpp"
#include "Satellites-static_automoc.dir/moc_SatellitesImpo_RCKFVNAOT67VSP.cpp"
